GarageGuru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('messages/', views.messages, name='messages'),
    path('profile/<int:user_id>', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.posts_detail, name='detail'),
    # path('posts/create/', views.PostCreate.as_view(), name='posts_create'),
    path('posts/create/', views.posts_create, name='posts_create'),
    path('posts/<int:pk>/update/', views.PostUpdate.as_view(), name='posts_update'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='posts_delete'),
    path('posts/<int:post_id>/add_photo/', views.add_photo, name='add_photo'),
    path('posts/<int:post_id>/delete_photo/<int:photo_id>', views.delete_photo, name='delete_photo'),
    path('posts/<int:post_id>/add_comment/<int:user_id>', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/commentDelete/<int:comment_id>', views.delete_comment, name='comment_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('posts/<int:post_id>/add_like/<int:user_id>', views.add_like, name='add_like'),
    path('posts/<int:post_id>/add_like_detail/<int:user_id>',views.add_like_detail, name='add_like_detail'),
    path('posts/<int:post_id>/likes', views.likes_detail, name='likes_detail'),
    path('profile/<int:user_id>/username', views.username_update, name='username_update'),
    path('profile/<int:user_id>/username/success', views.username_updated, name='username_updated'),
    path('profile/<int:user_id>/bio', views.bio_update, name='bio_update'),
    path('profile/<int:user_id>/bio/success', views.bio_updated, name='bio_updated'),
    path('profile/<int:user_id>/photo', views.user_photo_update, name='user_photo_update'),
    path('posts/<int:post_id>/likes', views.likes_detail, name='likes_detail'),
    path('send_message/', views.send_message, name='send_message'),   
    path('search/<str:hashtag>/', views.search_by_hashtag, name='search_by_hashtag'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

class UserDescription(models.Model):
    description = models.TextField(max_length=10000, blank=True, default='No User Bio')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class UserPhoto(models.Model):
    image = CloudinaryField('image', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"Photo for user_id: {self.user_id} @{self.image.url}"

class Post(models.Model):
    description = models.TextField(max_length=10000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-description']

class Photo(models.Model):
    image = CloudinaryField('image')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    def __str__(self):
        return f"Photo for post_id: {self.post_id} @{self.image.url}"

class Comment(models.Model):
    comment = models.TextField(max_length=10000)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'Message from {self.sender} to {self.recipient}'

main_app/forms.py
from django import forms
from .models import Post, Photo, UserPhoto, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = ["description"]

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["image"]

class UserPhotoForm(forms.ModelForm):
    class Meta:
        model = UserPhoto
        fields = ['image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

main_app/views.py
from django.contrib import messages as django_messages
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import UserManager
from .forms import PostForm, PhotoForm
from django.http import HttpResponse
from .forms import UserPhotoForm  # ensure this import is at the top

from .models import Post, Photo, Comment, Like, User, UserDescription, Message, UserPhoto
from .forms import CommentForm

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'garageguru57'

def home(request):
    posts = Post.objects.all()
    return render(request, 'home.html', { 'posts': posts })

@login_required
def messages(request):
    received_messages = Message.objects.filter(recipient=request.user)
    return render(request, 'messages.html', {'messages': received_messages})

@login_required
def profile(request, user_id):
    posts = Post.objects.filter(user=user_id)
    user_profile = User.objects.filter(id = user_id).values()[0]
    if UserDescription.objects.filter(user_id=user_id).exists():
        bio = UserDescription.objects.filter(user_id=user_id).values()[0]
    else:
        bio = {
            'description': 'No User Bio'
        }
    if UserPhoto.objects.filter(user_id=user_id).exists():
        profile_photo = UserPhoto.objects.filter(user_id=user_id).values()[0]
    else:
        profile_photo = []
    return render(request, 'profile.html', {'posts': posts, 'user_profile': user_profile, 'bio': bio, 'profile_photo': profile_photo})

@login_required
def posts_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    return render(request, 'posts/detail.html', { 'post': post, 'comment_form': comment_form })

@login_required
def add_photo(request, post_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        # If you use Cloudinary
        from cloudinary.uploader import upload
        result = upload(photo_file)
        url = result['secure_url']
        Photo.objects.create(image=url, post_id=post_id)  # Adjust this if your model uses FileField/ImageField!
        print("FILES RECEIVED:", request.FILES)
    return redirect('detail', post_id=post_id)



@login_required
def delete_photo(request, post_id, photo_id):
    photo = Photo.objects.get(id=photo_id)
    photo.delete()
    return redirect('detail', post_id=post_id)

@login_required
def search_by_hashtag(request, hashtag):
    posts = Post.objects.filter(description__icontains=f'#{hashtag}')
    context = {
        'hashtag': hashtag,
        'posts': posts,
    }
    return render(request, 'search_results.html', context)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

@login_required
def posts_create(request):
    error_message = ''
    if request.method == 'POST':
        form = PostForm(request.POST)
        photo_form = PhotoForm(request.POST, request.FILES)
        if form.is_valid() and photo_form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            photo = photo_form.save(commit=False)
            photo.post = post
            photo.save()
            return redirect('detail', post_id=post.id)
        else:
            error_message = 'Invalid new post'
    else:
        form = PostForm()
        photo_form = PhotoForm()
    context = {'form': form, 'photo_form': photo_form, 'error_message': error_message}
    return render(request, 'posts/create.html', context)

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['description']
    success_url = '/'

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'

@login_required
def send_message(request):
    if request.method == 'POST':
        recipient_username = request.POST['recipient']
        content = request.POST['content']
        try:
            recipient = User.objects.get(username=recipient_username)
        except User.DoesNotExist:
            django_messages.error(
                request, f'User with username {recipient_username} does not exist.')
            return redirect('send_message')
        message = Message(sender=request.user, recipient=recipient, content=content)
        message.save()
        django_messages.success(request, 'Message sent successfully!')
        return redirect('messages')
    return render(request, 'send_message.html')

@login_required
def add_comment(request, post_id, user_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.post_id = post_id
        new_comment.user_id = user_id
        new_comment.save()
    return redirect('detail', post_id=post_id)

@login_required
def delete_comment(request, post_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect('detail', post_id=post_id)

@login_required
def add_like(request, post_id, user_id):
    like_list = []
    idx = 0
    for x in Like.objects.filter(post_id=post_id):
        like_list.append(Like.objects.filter(post_id=post_id).values("user_id")[idx]['user_id'])
        idx += 1

    if user_id in like_list:
        Like.objects.filter(post_id=post_id, user_id=user_id).delete()
    else:
        new_like = Like()
        new_like.post_id = post_id
        new_like.user_id = user_id
        new_like.save()

    return redirect('home')

def add_like_detail(request, post_id, user_id):
    like_list = []
    idx = 0
    for x in Like.objects.filter(post_id=post_id):
        like_list.append(Like.objects.filter(post_id=post_id).values("user_id")[idx]['user_id'])
        idx += 1

    if user_id in like_list:
        Like.objects.filter(post_id=post_id, user_id=user_id).delete()
    else:
        new_like = Like()
        new_like.post_id = post_id
        new_like.user_id = user_id
        new_like.save()

    return redirect('detail', post_id=post_id)

def likes_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    return render(request, 'likes/detail.html', { 'post': post })

def username_update(request, user_id):
    return render(request, 'main_app/username_form.html')

def username_updated(request, user_id):
    this_user = User.objects.get(id=user_id)
    this_user.username = request.POST['username']
    for user in User.objects.values():
        if user['username'] == request.POST['username']:
            return redirect('username_update', user_id=user_id)
    this_user.save()
    return redirect('profile', user_id=user_id)

def bio_update(request, user_id):
    return render(request, 'main_app/bio_form.html')

def bio_updated(request, user_id):
    if not UserDescription.objects.filter(user_id=user_id).exists():
        this_user = UserDescription(description=request.POST['description'], user_id=user_id)
        this_user.save()
        return redirect('profile', user_id=user_id)
    else:
        this_user = UserDescription.objects.get(user_id=user_id)
        this_user.description = request.POST['description']
        this_user.save()
        return redirect('profile', user_id=user_id)


@login_required
def user_photo_update(request, user_id):
    if request.method == 'POST':
        form = UserPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            user_photo, created = UserPhoto.objects.get_or_create(user_id=user_id)
            user_photo.image = form.cleaned_data['image']
            user_photo.save()
        else:
            print(form.errors)  # Log errors to the Heroku logs
            # Optionally return errors as HTTP response for debugging
            return HttpResponse(form.errors, status=400)
    return redirect('profile', user_id=user_id)

@login_required
def user_photo_update(request, user_id):
    if request.method == 'POST':
        form = UserPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            user_photo, created = UserPhoto.objects.get_or_create(user_id=user_id)
            user_photo.image = form.cleaned_data['image']
            user_photo.save()
            return redirect('profile', user_id=user_id)
    else:
        form = UserPhotoForm()
    return render(request, 'main_app/user_photo_form.html', {'form': form})

main_app/templates/posts/create.html
{% extends 'base.html' %}
{% block content %}

<h1>Add A Post</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <p>
    <label for="id_description">Description:</label>
    <textarea
      name="description"
      cols="40"
      rows="10"
      maxlength="10000"
      required=""
      id="id_description"
    >{{ form.description.value }}</textarea>
  </p>

  <label for="id_image">Photo:</label><br>
  <input type="file" name="image" id="id_image" required />
  <br /><br />

  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>
</form>

{% endblock %}

main_app/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Post Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ post.name }}</span>
    <p>{{ post.description }}</p><br><br>
    {% if user.id in post.like_list_generator %}
    <form action="{% url 'add_like_detail' post.id user.id %}" method="post">
        {% csrf_token %}
        <!-- <button type="submit">Unlike</button> -->
  <button class="btn waves-effect waves-light" type="submit" name="action">
    <i class="material-icons dp48 center">favorite</i>
  </button>
    </form>
    {% else %}  
    <form action="{% url 'add_like_detail' post.id user.id %}" method="post">
        {% csrf_token %}
        <!-- <button type="submit">Like</button> -->
  <button class="btn waves-effect waves-light" type="submit" name="action">
    <i class="material-icons dp48 center">favorite_border</i>
  </button>
    </form>
    {% endif %}
    <a href="/posts/{{ post.id }}/likes"><p>{{ post.like_set.count }} Likes</p></a>
  </div>

  {% if post.user_id == request.user.id %}
  <div class="card-action">
    <a href="{% url 'posts_update' post.id %}">Edit</a>
    <a href="{% url 'posts_delete' post.id %}">Delete</a>
  </div>
  {% endif %}
  </div>

  {% for photo in post.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.image.url}}">
    {% if post.user_id == request.user.id %}
    <form action="{% url 'delete_photo' post.id photo.id %}" method="POST">
      {% csrf_token %}
      <!-- <input type="submit" class="btn" value="Delete photo"> -->
  <button class="btn waves-effect waves-light" type="submit" name="action">Delete Photo
    <i class="material-icons dp48 right">delete</i>
  </button><br><br>
    </form> 
    {% endif %}
  {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
  {% endfor %}
 
{% if post.user_id == request.user.id %}
<form action="{% url 'add_photo' post.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
  {% csrf_token %}
  <input type="file" name="photo-file" required>
  <br><br>
  <!-- <input type="submit" class="btn" value="Upload Photo"> -->
  <button class="btn waves-effect waves-light" type="submit" name="action">Add Photo
    <i class="material-icons dp48 right">add_a_photo</i>
  </button>
</form>
{% endif %}

<form action="{% url 'add_comment' post.id user.id%}" method="post">
  {% csrf_token %}
  {{ comment_form.as_p }}
  <!-- <input type="submit" class="btn" value="Add Comment"> -->
  <button class="btn waves-effect waves-light" type="submit" name="action">Add Comment
    <i class="material-icons dp48 right">comment</i>
  </button>
</form>



<h4>Comments:</h4>
{% if not post.comment_set.all %}
  <h6>Be the first to comment!</h6>
{% endif %}
{% for comment in post.comment_set.all %}
<div class="card">
  <a href="{% url 'profile' comment.user.id %}">
  <div class="card-title" style="margin: 0 0 0 10px;">{{comment.user.username}}</div>
  </a>
  <div class="card-content">{{comment.comment}}</div>
  <div class="card-action">
    <a href="{% url 'comment_delete' post.id comment.id %}">Delete</a>
  </div>
</div>
{% endfor %}

{% endblock %}